### ISSUE TITLE
PokeDex Not working?

### ISSUE THREAD

**Issue by FinKey101** [Wonder-Toast/Pokebot#2]
So I've noticed that majority of the guys On my discord who try use the p.pokedex command isn't working. I went into the p.info then PokeDex to ensure that we were doing the right command correctly, which by the looks of it we are. We tried pulling p.inventory, and phrasing the names word for word. We tried to see if other commands like p.binfo (berry) to see if it works and it does so this seems to be a separate problem for just the p.pokedex (name) command. We even went as far as trying to see if other similar wording commands might work as well p.pokemonindex, p.pindex,!dex, all sorts of things. Got like 90 guys in my discord and we're trying to figure it out. It seems to check out that ALL other commands work perfectly other than that! But we would really love see our info on our pokemon when we battle.

**Comment by YaBoyWonder** [comment]
so pokedex was offlline due to my module being wacky for some reason. I have brought it back online now though!  

![](https://i.imgur.com/TY08lFR.png)
